# Generated by Django 5.2.17 on 2026-10-02 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64, unique=True, verbose_name='会话摘要')),
                ('encrypted_session_key', models.TextField(verbose_name='本次登录加密微信会话密钥')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='失效时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学员会话',
                'verbose_name_plural': '学员会话',
            },
        ),
        migrations.CreateModel(
            name='WeChatIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=64, verbose_name='小程序 AppID')),
                ('openid', models.CharField(max_length=128, verbose_name='微信身份')),
                ('encrypted_session_key', models.TextField(verbose_name='加密微信会话密钥')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新登录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wechat_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学员微信身份',
                'verbose_name_plural': '学员微信身份',
                'constraints': [models.UniqueConstraint(fields=('app_id', 'openid'), name='unique_wechat_identity')],
            },
        ),
    ]
