# Generated by Django 5.2.17 on 2026-10-02 06:57

import django.db.models.deletion
from django.db import migrations, models


def link_unambiguous_sessions(apps, schema_editor):
    identity_model = apps.get_model('accounts', 'WeChatIdentity')
    session_model = apps.get_model('accounts', 'StudentSession')
    for row in identity_model.objects.values('user_id').annotate(total=models.Count('id')).filter(total=1).iterator():
        identity_id = identity_model.objects.get(user_id=row['user_id']).pk
        session_model.objects.filter(user_id=row['user_id'], identity__isnull=True).update(identity_id=identity_id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentsession_wechatidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='accounts.wechatidentity'),
        ),
        migrations.RunPython(link_unambiguous_sessions, migrations.RunPython.noop),
    ]
