# Generated by Django 5.2.17 on 2026-10-02 07:27

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentsession_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
            ],
            options={
                'verbose_name': '学员账号启停',
                'verbose_name_plural': '学员账号启停',
                'permissions': (('set_student_status', '可以受控启停学员账户'),),
                'proxy': True,
                'default_permissions': ('view',),
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
