# Generated by Django 5.2.17 on 2026-10-02 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitlements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='用途说明')),
                ('state', models.CharField(choices=[('awaiting_receipt', '待领取确认'), ('received', '已领取待启用'), ('enabled', '已启用'), ('disabled', '已禁用'), ('void', '已作废')], default='awaiting_receipt', max_length=24, verbose_name='批次状态')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='状态版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='领取确认时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='状态更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activation_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_activation_batches', to=settings.AUTH_USER_MODEL, verbose_name='领取确认者')),
            ],
            options={
                'verbose_name': '激活码批次',
                'verbose_name_plural': '激活码批次',
                'ordering': ('-created_at', 'id'),
                'permissions': (('generate_activationbatch', '可以生成并一次下载激活码'), ('receive_activationbatch', '可以确认激活码文件已领取'), ('enable_activationbatch', '可以启用已领取批次'), ('disable_activationbatch', '可以禁用激活码批次'), ('void_activationbatch', '可以作废未领取批次')),
            },
        ),
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digest', models.CharField(max_length=64, unique=True, verbose_name='激活码摘要')),
                ('mask', models.CharField(max_length=32, verbose_name='掩码')),
                ('state', models.CharField(choices=[('unused', '未使用'), ('redeemed', '已兑换'), ('disabled', '单码禁用')], default='unused', max_length=16, verbose_name='使用状态')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='兑换时间')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='单码禁用时间')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='禁用理由')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='activation.activationbatch', verbose_name='批次')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_activation_codes', to=settings.AUTH_USER_MODEL, verbose_name='兑换学员')),
            ],
            options={
                'verbose_name': '激活码（仅掩码）',
                'verbose_name_plural': '激活码（仅掩码）',
                'permissions': (('disable_activationcode', '可以禁用未兑激活码'),),
            },
        ),
        migrations.CreateModel(
            name='ActivationRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='redemption', to='activation.activationcode', verbose_name='已兑码')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='activation_redemption', to='entitlements.entitlementsource', verbose_name='永久权益来源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activation_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='学员')),
            ],
            options={
                'verbose_name': '激活码兑换历史',
                'verbose_name_plural': '激活码兑换历史',
                'ordering': ('-redeemed_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='activationbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 500)), name='activation_batch_quantity'),
        ),
        migrations.AddConstraint(
            model_name='activationbatch',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('awaiting_receipt', 'received', 'enabled', 'disabled', 'void'))), name='activation_batch_state'),
        ),
        migrations.AddConstraint(
            model_name='activationcode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('redeemed_at__isnull', False), ('redeemed_by__isnull', False), ('state', 'redeemed')), models.Q(('redeemed_at__isnull', True), ('redeemed_by__isnull', True), ('state__in', ('unused', 'disabled'))), _connector='OR'), name='activation_code_used_state'),
        ),
    ]
