# Generated by Django 5.2.17 on 2026-10-01 18:32

import content.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='篇目编号')),
                ('title', models.CharField(max_length=160, verbose_name='篇目名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '文言篇目',
                'verbose_name_plural': '文言篇目',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='分类编号')),
                ('name', models.CharField(max_length=120, verbose_name='分类名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '文学分类',
                'verbose_name_plural': '文学分类',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('source', models.CharField(choices=[('literature', '文学常识'), ('classical', '文言文')], max_length=20, verbose_name='来源')),
                ('type', models.CharField(choices=[('fact', '常识'), ('word', '字词'), ('translation', '翻译')], max_length=20, verbose_name='题型')),
                ('tag', models.CharField(blank=True, max_length=80, verbose_name='标签')),
                ('stem', models.TextField(help_text='用 {{0}}、{{1}} 等表示答案位置，可重复引用相同位置。', verbose_name='题干')),
                ('answers', models.JSONField(default=list, verbose_name='答案')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('id', models.CharField(default=content.models.new_question_id, max_length=64, primary_key=True, serialize=False, verbose_name='题目编号')),
                ('is_published', models.BooleanField(default=False, verbose_name='已发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='草稿/发布更新时间')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_questions', to='content.article', verbose_name='文言篇目')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_questions', to='content.category', verbose_name='文学分类')),
            ],
            options={
                'verbose_name': '题目草稿',
                'verbose_name_plural': '题目草稿',
                'ordering': ('sort_order', 'id'),
                'permissions': [('publish_question', '可以发布及下架题目'), ('import_question', '可以导入题目草稿')],
            },
        ),
        migrations.CreateModel(
            name='QuestionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('literature', '文学常识'), ('classical', '文言文')], max_length=20, verbose_name='来源')),
                ('type', models.CharField(choices=[('fact', '常识'), ('word', '字词'), ('translation', '翻译')], max_length=20, verbose_name='题型')),
                ('tag', models.CharField(blank=True, max_length=80, verbose_name='标签')),
                ('stem', models.TextField(help_text='用 {{0}}、{{1}} 等表示答案位置，可重复引用相同位置。', verbose_name='题干')),
                ('answers', models.JSONField(default=list, verbose_name='答案')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='修订号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_revisions', to='content.article', verbose_name='文言篇目')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_revisions', to='content.category', verbose_name='文学分类')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_question_revisions', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='content.question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '发布修订（只读）',
                'verbose_name_plural': '发布修订（只读）',
                'ordering': ('question_id', '-version'),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.questionrevision', verbose_name='当前发布修订'),
        ),
        migrations.AddConstraint(
            model_name='questionrevision',
            constraint=models.UniqueConstraint(fields=('question', 'version'), name='content_unique_question_revision'),
        ),
    ]
