# Generated by Django 5.2.17 on 2026-10-02 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('page_size', models.PositiveSmallIntegerField(default=20, help_text='文言每篇目全部题型合计提供这一数量的免费题。', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='每页题数／统一免费题量')),
                ('daily_target', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='默认每日目标')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='考试日期')),
            ],
            options={
                'verbose_name': '学习配置',
                'verbose_name_plural': '学习配置',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='content_learning_config_singleton'), models.CheckConstraint(condition=models.Q(('page_size__gte', 1), ('page_size__lte', 100)), name='content_learning_page_size_range'), models.CheckConstraint(condition=models.Q(('daily_target__gte', 1), ('daily_target__lte', 1000)), name='content_learning_daily_target_range')],
            },
        ),
    ]
