# Generated by Django 5.2.17 on 2026-10-02 06:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(db_index=True, verbose_name='上海学习日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学习活动',
                'verbose_name_plural': '学习活动',
                'constraints': [models.UniqueConstraint(fields=('user', 'question', 'study_date'), name='learning_unique_daily_activity')],
            },
        ),
        migrations.CreateModel(
            name='LearningPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('writing', '默写'), ('reciting', '背诵')], default='writing', max_length=10, verbose_name='学习模式')),
                ('daily_target', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='每日目标')),
                ('version', models.PositiveBigIntegerField(default=0, verbose_name='版本')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学习偏好',
                'verbose_name_plural': '学习偏好',
                'constraints': [models.CheckConstraint(condition=models.Q(('mode__in', ('writing', 'reciting'))), name='learning_valid_mode'), models.CheckConstraint(condition=models.Q(('daily_target__gte', 1), ('daily_target__lte', 1000)), name='learning_valid_target')],
            },
        ),
        migrations.CreateModel(
            name='QuestionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False, verbose_name='收藏')),
                ('mastered', models.BooleanField(default=False, verbose_name='掌握')),
                ('version', models.PositiveBigIntegerField(default=0, verbose_name='版本')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学习状态',
                'verbose_name_plural': '学习状态',
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='learning_unique_question_state')],
            },
        ),
    ]
