# Generated by Django 5.2.17 on 2026-10-02 05:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitlementSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('all_chinese', '全部语文题库')], default='all_chinese', max_length=32, verbose_name='权益范围')),
                ('source_type', models.CharField(choices=[('activation', '激活码'), ('payment', '付款')], max_length=16, verbose_name='来源类型')),
                ('source_id', models.CharField(max_length=128, verbose_name='来源业务编号')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时间（永久为空）')),
                ('status', models.CharField(choices=[('active', '有效'), ('revoked', '已撤销')], default='active', max_length=16, verbose_name='来源状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发放时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='撤销理由')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_entitlement_sources', to=settings.AUTH_USER_MODEL, verbose_name='发放操作者')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_entitlement_sources', to=settings.AUTH_USER_MODEL, verbose_name='撤销操作者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_sources', to=settings.AUTH_USER_MODEL, verbose_name='学员')),
            ],
            options={
                'verbose_name': '永久权益来源',
                'verbose_name_plural': '永久权益来源',
                'ordering': ('-created_at', 'id'),
                'permissions': (('grant_entitlementsource', '可以通过受控服务发放永久权益'), ('revoke_entitlementsource', '可以撤销指定永久权益来源')),
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32, verbose_name='操作')),
                ('order_id', models.CharField(blank=True, max_length=128, verbose_name='本地订单编号')),
                ('details', models.JSONField(default=dict, verbose_name='业务记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_entitlement_events', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_events', to=settings.AUTH_USER_MODEL, verbose_name='学员')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='entitlements.entitlementsource', verbose_name='权益来源')),
            ],
            options={
                'verbose_name': '权益业务审计',
                'verbose_name_plural': '权益业务审计',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OpeningReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('all_chinese', '全部语文题库')], default='all_chinese', max_length=32, verbose_name='权益范围')),
                ('order_id', models.CharField(max_length=128, verbose_name='本地订单编号')),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='占位时间')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='解除时间')),
                ('release_reason', models.CharField(blank=True, max_length=32, verbose_name='解除依据')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_reservations', to=settings.AUTH_USER_MODEL, verbose_name='学员')),
            ],
            options={
                'verbose_name': '支付开通占位',
                'verbose_name_plural': '支付开通占位',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default='all-chinese', max_length=64, primary_key=True, serialize=False, verbose_name='商品编号')),
                ('scope', models.CharField(choices=[('all_chinese', '全部语文题库')], default='all_chinese', max_length=32, unique=True, verbose_name='权益范围')),
                ('name', models.CharField(default='语文全题库永久权益', max_length=120, verbose_name='商品名称')),
                ('price_fen', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='金额（分）')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('platform_product_id', models.CharField(blank=True, max_length=128, verbose_name='平台商品编号')),
                ('platform_synced_price_fen', models.PositiveIntegerField(blank=True, null=True, verbose_name='最近同步金额（分）')),
                ('platform_sync_state', models.CharField(choices=[('pending', '待同步'), ('synced', '已同步')], default='pending', max_length=16, verbose_name='同步状态')),
                ('platform_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='同步确认时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '全题库商品',
                'verbose_name_plural': '全题库商品',
                'permissions': (('sync_product', '可以确认平台商品价格已同步'),),
                'constraints': [models.CheckConstraint(condition=models.Q(('scope', 'all_chinese')), name='ent_product_scope'), models.CheckConstraint(condition=models.Q(('price_fen__gt', 0)), name='ent_product_positive_price')],
            },
        ),
        migrations.AddConstraint(
            model_name='entitlementsource',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='ent_unique_source'),
        ),
        migrations.AddConstraint(
            model_name='entitlementsource',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True)), name='ent_permanent_no_expiry'),
        ),
        migrations.AddConstraint(
            model_name='entitlementsource',
            constraint=models.CheckConstraint(condition=models.Q(('scope', 'all_chinese')), name='ent_source_scope'),
        ),
        migrations.AddConstraint(
            model_name='entitlementsource',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ('activation', 'payment'))), name='ent_source_type'),
        ),
        migrations.AddConstraint(
            model_name='entitlementsource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('status', 'revoked')), _connector='OR'), name='ent_source_status'),
        ),
        migrations.AddConstraint(
            model_name='openingreservation',
            constraint=models.UniqueConstraint(fields=('user', 'scope'), name='ent_unique_user_reservation'),
        ),
        migrations.AddConstraint(
            model_name='openingreservation',
            constraint=models.CheckConstraint(condition=models.Q(('scope', 'all_chinese')), name='ent_reservation_scope'),
        ),
    ]
