# Generated by Django 5.2.17 on 2026-10-02 06:54

import django.db.models.deletion
import django.utils.timezone
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_studentsession_wechatidentity'),
        ('entitlements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=payments.models.order_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=120)),
                ('scope', models.CharField(default='all_chinese', max_length=32)),
                ('price_fen', models.PositiveIntegerField()),
                ('platform_product_id', models.CharField(max_length=128)),
                ('app_id', models.CharField(max_length=64)),
                ('environment', models.PositiveSmallIntegerField(default=0)),
                ('channel', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=16)),
                ('status', models.CharField(choices=[('created', '本地待支付'), ('preparing', '平台处理中'), ('paid', '已付款待发权'), ('fulfilled', '已开通'), ('closed', '平台确认关闭'), ('refunded', '平台已退款'), ('review', '待人工核查')], default='created', max_length=16)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('sign_data', models.TextField(blank=True)),
                ('platform_order_id', models.CharField(blank=True, max_length=128)),
                ('transaction_id', models.CharField(blank=True, max_length=128)),
                ('last_platform_status', models.IntegerField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.wechatidentity')),
                ('prepared_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.studentsession')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entitlements.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '付款订单',
                'verbose_name_plural': '付款订单',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('query', '查单'), ('deliver', '通知发货')], max_length=16)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('done', '完成'), ('failed', '需核查')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_token', models.CharField(blank=True, max_length=64)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='payments.order')),
            ],
            options={
                'verbose_name': '支付补偿任务',
                'verbose_name_plural': '支付补偿任务',
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('price_fen__gt', 0)), name='payment_positive_price'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('scope', 'all_chinese')), name='payment_single_scope'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('environment__in', (0, 1))), name='payment_environment'),
        ),
        migrations.AddConstraint(
            model_name='paymenttask',
            constraint=models.UniqueConstraint(fields=('order', 'kind'), name='payment_unique_task'),
        ),
    ]
