# Generated by Django 5.2.17 on 2026-10-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='configuration_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
