# Generated by Django 5.2.17 on 2026-10-02 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentsession_identity'),
        ('entitlements', '0001_initial'),
        ('payments', '0002_order_configuration_digest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokenCache',
            fields=[
                ('app_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('ciphertext', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '微信接口令牌缓存（加密）',
                'verbose_name_plural': '微信接口令牌缓存（加密）',
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('request_digest', models.CharField(max_length=64)),
                ('outcome', models.CharField(max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '支付平台事件',
                'verbose_name_plural': '支付平台事件',
                'ordering': ('-created_at', 'key'),
            },
        ),
        migrations.AlterModelOptions(
            name='paymenttask',
            options={'permissions': (('reschedule_paymenttask', '可以确认并重调度失败支付任务'),), 'verbose_name': '支付补偿任务', 'verbose_name_plural': '支付补偿任务'},
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('platform_order_id', ''), _negated=True), fields=('platform_order_id',), name='payment_platform_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_id', ''), _negated=True), fields=('transaction_id',), name='payment_transaction_unique'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payments.order'),
        ),
    ]
