# Generated by Django 5.2.17 on 2026-10-02 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_learningconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeRound',
            fields=[
                ('source', models.CharField(choices=[('literature', '文学常识'), ('classical', '文言文')], max_length=20, verbose_name='来源')),
                ('question_type', models.CharField(blank=True, choices=[('', '全部题型'), ('fact', '常识'), ('word', '字词'), ('translation', '翻译')], default='', max_length=20, verbose_name='题型')),
                ('mode', models.CharField(choices=[('writing', '默写'), ('reciting', '背诵')], max_length=16, verbose_name='模式')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_size', models.PositiveSmallIntegerField(verbose_name='固定每组题数')),
                ('item_count', models.PositiveIntegerField(verbose_name='固定题量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.article', verbose_name='篇目')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.category', verbose_name='分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='学员')),
            ],
            options={
                'verbose_name': '随机轮次',
                'verbose_name_plural': '随机轮次',
            },
        ),
        migrations.CreateModel(
            name='ResumePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('literature', '文学常识'), ('classical', '文言文')], max_length=20, verbose_name='来源')),
                ('question_type', models.CharField(blank=True, choices=[('', '全部题型'), ('fact', '常识'), ('word', '字词'), ('translation', '翻译')], default='', max_length=20, verbose_name='题型')),
                ('mode', models.CharField(choices=[('writing', '默写'), ('reciting', '背诵')], max_length=16, verbose_name='模式')),
                ('group_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='组号')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.article', verbose_name='篇目')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.category', verbose_name='分类')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.question', verbose_name='续学题目')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practiceround', verbose_name='轮次')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='学员')),
            ],
            options={
                'verbose_name': '续学位置',
                'verbose_name_plural': '续学位置',
            },
        ),
        migrations.CreateModel(
            name='RoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='固定序号')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.question', verbose_name='题目')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.questionrevision', verbose_name='固定修订')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='practice.practiceround', verbose_name='轮次')),
            ],
            options={
                'verbose_name': '轮次题目',
                'verbose_name_plural': '轮次题目',
                'ordering': ('position',),
            },
        ),
        migrations.AddConstraint(
            model_name='practiceround',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('article__isnull', True), ('category__isnull', False), ('question_type__in', ('', 'fact')), ('source', 'literature')), models.Q(('article__isnull', False), ('category__isnull', True), ('question_type__in', ('', 'fact', 'word', 'translation')), ('source', 'classical')), _connector='OR'), name='practice_round_scope'),
        ),
        migrations.AddConstraint(
            model_name='practiceround',
            constraint=models.CheckConstraint(condition=models.Q(('group_size__gte', 1), ('group_size__lte', 100)), name='practice_round_group_size'),
        ),
        migrations.AddConstraint(
            model_name='practiceround',
            constraint=models.CheckConstraint(condition=models.Q(('item_count__gte', 1), ('item_count__lte', 10000)), name='practice_round_item_count'),
        ),
        migrations.AddConstraint(
            model_name='practiceround',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ('writing', 'reciting'))), name='practice_round_mode'),
        ),
        migrations.AddConstraint(
            model_name='resumeposition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('article__isnull', True), ('category__isnull', False), ('question_type__in', ('', 'fact')), ('source', 'literature')), models.Q(('article__isnull', False), ('category__isnull', True), ('question_type__in', ('', 'fact', 'word', 'translation')), ('source', 'classical')), _connector='OR'), name='practice_resume_scope'),
        ),
        migrations.AddConstraint(
            model_name='resumeposition',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='practice_resume_version'),
        ),
        migrations.AddConstraint(
            model_name='resumeposition',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ('writing', 'reciting'))), name='practice_resume_mode'),
        ),
        migrations.AddConstraint(
            model_name='resumeposition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group_index__isnull', True), ('round__isnull', True)), models.Q(('group_index__gte', 1), ('group_index__isnull', False), ('round__isnull', False)), _connector='OR'), name='practice_resume_random_context'),
        ),
        migrations.AddConstraint(
            model_name='rounditem',
            constraint=models.UniqueConstraint(fields=('round', 'position'), name='practice_round_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='rounditem',
            constraint=models.UniqueConstraint(fields=('round', 'question'), name='practice_round_question_unique'),
        ),
        migrations.AddConstraint(
            model_name='rounditem',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 10000)), name='practice_item_position_range'),
        ),
    ]
